<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProduitsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $produits = [
            [
                'slug' => 'oignon-safari',
                'nom' => 'Oignon',
                'variete' => 'Safari',
                'description' => 'L\'oignon Safari est une variété africaine réputée pour sa saveur intense et son arôme exceptionnel. Cultivé biologiquement sur nos terres en Côte d\'Ivoire, cet oignon se distingue par sa forme ronde et sa texture ferme, parfaite pour la cuisine traditionnelle.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur intense et piquante avec des notes aromatiques caractéristiques, idéal pour relever les plats',
                'conservation' => 'Conserver dans un endroit sec et aéré à température ambiante. Peut se conserver 3-4 semaines.',
                'saison' => 'Toute l\'année (production continue)',
                'usage' => 'Crus en salade, cuits dans les plats traditionnels africains, marinades, soupes et ragoûts',
                'conditionnement' => json_encode(['20kg', '45kg']),
                'image' => '/img/produits/oignon-safari.jpg',
                'prix' => 1500.00,
                'bienfaits' => json_encode([
                    'Riche en antioxydants (quercétine) qui protègent contre les maladies cardiovasculaires',
                    'Contient des composés sulfurés qui renforcent le système immunitaire',
                    'Aide à réguler la glycémie et à réduire le cholestérol',
                    'Propriétés anti-inflammatoires et antibactériennes naturelles',
                    'Excellente source de vitamine C et de fibres alimentaires'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'gombo-hire',
                'nom' => 'Gombo',
                'variete' => 'Hiré',
                'description' => 'Le gombo Hiré est une variété africaine de gombo particulièrement appréciée pour sa texture tendre et son goût délicat. Cette variété bio produit des gousses vertes de taille moyenne, parfaites pour la cuisine traditionnelle.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Goût légèrement amer et terreux, texture mucilagineuse caractéristique',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 3-5 jours.',
                'saison' => 'Juin à octobre',
                'usage' => 'Soupes, ragoûts, plats traditionnels africains, accompagnements',
                'conditionnement' => json_encode(['18kg', '40kg']),
                'image' => '/img/produits/gombo-hire.jpg',
                'prix' => 1200.00,
                'bienfaits' => json_encode([
                    'Excellente source de fibres solubles qui régulent la glycémie',
                    'Riche en vitamine K essentielle pour la coagulation sanguine',
                    'Contient de la vitamine C qui renforce le système immunitaire',
                    'Propriétés mucilagineuses qui apaisent le système digestif',
                    'Faible en calories et riche en antioxydants'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'tomate-cobra',
                'nom' => 'Tomate',
                'variete' => 'Cobra',
                'description' => 'La tomate Cobra est une variété hybride robuste, parfaite pour la transformation et la consommation fraîche. Cultivée biologiquement, elle se caractérise par sa forme allongée et sa chair ferme, idéale pour les sauces et les salades.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur équilibrée, légèrement acide avec une douceur naturelle',
                'conservation' => 'Conserver à température ambiante jusqu\'à maturation, puis au réfrigérateur. Consommer dans les 5-7 jours.',
                'saison' => 'Toute l\'année (serres)',
                'usage' => 'Salades, sauces, coulis, jus, plats cuisinés',
                'conditionnement' => json_encode(['20kg', '50kg']),
                'image' => '/img/produits/tomate-cobra.jpg',
                'prix' => 1800.00,
                'bienfaits' => json_encode([
                    'Riche en lycopène, un antioxydant puissant qui protège contre le cancer',
                    'Excellente source de vitamine C qui renforce le système immunitaire',
                    'Contient du potassium qui régule la pression artérielle',
                    'Riche en vitamine A essentielle pour la vision et la peau',
                    'Propriétés anti-inflammatoires et cardioprotectrices'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'aubergine-djemba',
                'nom' => 'Aubergine',
                'variete' => 'Djemba',
                'description' => 'L\'aubergine Djemba est une variété africaine traditionnelle, reconnaissable à sa forme allongée et sa couleur violet foncé. Cultivée biologiquement, elle est particulièrement appréciée pour sa chair tendre et son goût délicat.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur douce et légèrement amère, chair tendre et fondante',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 5-7 jours.',
                'saison' => 'Mai à octobre',
                'usage' => 'Ragoûts, grillades, purées, plats traditionnels africains',
                'conditionnement' => json_encode(['20kg', '50kg']),
                'image' => '/img/produits/aubergine-djemba.jpg',
                'prix' => 1600.00,
                'bienfaits' => json_encode([
                    'Riche en nasunine, un antioxydant qui protège les cellules cérébrales',
                    'Excellente source de fibres qui favorisent la digestion',
                    'Contient du potassium qui aide à réguler la pression artérielle',
                    'Faible en calories et riche en vitamines B',
                    'Propriétés diurétiques et détoxifiantes'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'poivron-california',
                'nom' => 'Poivron',
                'variete' => 'California',
                'description' => 'Le poivron California est une variété de poivron doux particulièrement appréciée pour sa chair épaisse et sa saveur sucrée. Cultivé biologiquement, il se caractérise par sa forme carrée et sa couleur rouge vif à maturité.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur douce et sucrée, chair épaisse et croquante, sans piquanté',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 7-10 jours.',
                'saison' => 'Toute l\'année (serres)',
                'usage' => 'Salades, plats cuisinés, farcis, grillades, sauces',
                'conditionnement' => json_encode(['15kg', '25kg']),
                'image' => '/img/produits/poivron-california.jpg',
                'prix' => 2200.00,
                'bienfaits' => json_encode([
                    'Excellente source de vitamine C qui renforce le système immunitaire',
                    'Riche en bêta-carotène qui améliore la vision et la peau',
                    'Contient de la vitamine B6 qui booste le métabolisme',
                    'Propriétés antioxydantes qui protègent contre le vieillissement',
                    'Faible en calories et riche en fibres alimentaires'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'piment-big-sun',
                'nom' => 'Piment',
                'variete' => 'Big Sun',
                'description' => 'Le piment Big Sun est une variété africaine de piment doux, parfaite pour ceux qui apprécient la saveur du piment sans la forte piquanté. Cultivé biologiquement, sa forme allongée et sa couleur rouge vif en font un ingrédient visuellement attrayant.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur douce et légèrement piquante, arôme fruité caractéristique',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 7-10 jours.',
                'saison' => 'Juin à novembre',
                'usage' => 'Salades, plats cuisinés, marinades, sauces',
                'conditionnement' => json_encode(['15kg', '25kg']),
                'image' => '/img/produits/piment-big-sun.jpg',
                'prix' => 2000.00,
                'bienfaits' => json_encode([
                    'Riche en capsaïcine qui stimule le métabolisme et favorise la perte de poids',
                    'Excellente source de vitamine C qui renforce le système immunitaire',
                    'Contient de la vitamine A essentielle pour la vision',
                    'Propriétés anti-inflammatoires et analgésiques',
                    'Aide à améliorer la circulation sanguine'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'choux-kk-cross',
                'nom' => 'Choux',
                'variete' => 'KK Cross',
                'description' => 'Le chou KK Cross est une variété hybride robuste, parfaite pour les climats chauds. Cultivé biologiquement, il produit des têtes compactes et fermes, avec des feuilles croquantes et savoureuses.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur douce et légèrement sucrée, texture croquante',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 10-14 jours.',
                'saison' => 'Octobre à mars',
                'usage' => 'Salades, soupes, plats cuisinés, fermentations',
                'conditionnement' => json_encode(['25kg', '60kg']),
                'image' => '/img/produits/choux-kk-cross.jpg',
                'prix' => 1400.00,
                'bienfaits' => json_encode([
                    'Riche en glucosinolates qui ont des propriétés anti-cancer',
                    'Excellente source de vitamine K essentielle pour la coagulation',
                    'Contient de la vitamine C qui renforce le système immunitaire',
                    'Riche en fibres qui favorisent la digestion',
                    'Propriétés anti-inflammatoires et détoxifiantes'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'concombre-tokyo',
                'nom' => 'Concombre',
                'variete' => 'Tokyo',
                'description' => 'Le concombre Tokyo est une variété japonaise adaptée aux climats africains. Cultivé biologiquement, il se caractérise par sa forme allongée, sa peau fine et sa chair croquante sans amertume.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur douce et rafraîchissante, texture croquante, sans amertume',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 7-10 jours.',
                'saison' => 'Toute l\'année (serres)',
                'usage' => 'Salades, jus, accompagnements frais, pickles',
                'conditionnement' => json_encode(['30kg', '60kg']),
                'image' => '/img/produits/concombre-tokyo.jpg',
                'prix' => 1300.00,
                'bienfaits' => json_encode([
                    'Très riche en eau (95%) pour une excellente hydratation',
                    'Contient de la silice qui renforce les tissus conjonctifs',
                    'Riche en antioxydants qui protègent contre le vieillissement',
                    'Propriétés diurétiques et détoxifiantes',
                    'Faible en calories et excellent pour la perte de poids'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'carotte-new-kuroda',
                'nom' => 'Carotte',
                'variete' => 'New Kuroda',
                'description' => 'La carotte New Kuroda est une variété asiatique adaptée aux climats chauds. Cultivée biologiquement, elle produit des racines orange vif, sucrées et croquantes, parfaites pour la consommation fraîche et la transformation.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur sucrée et croquante, arôme caractéristique de carotte',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 10-14 jours.',
                'saison' => 'Toute l\'année (production continue)',
                'usage' => 'Salades, jus, soupes, plats cuisinés, snacking',
                'conditionnement' => json_encode(['5kg', '15kg']),
                'image' => '/img/produits/carotte-new-kuroda.jpg',
                'prix' => 1700.00,
                'bienfaits' => json_encode([
                    'Riche en bêta-carotène qui améliore la vision nocturne',
                    'Excellente source de vitamine A essentielle pour la peau',
                    'Contient des antioxydants qui protègent contre le cancer',
                    'Riche en fibres qui favorisent la digestion',
                    'Propriétés anti-inflammatoires et cardioprotectrices'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'haricot-cora',
                'nom' => 'Haricot',
                'variete' => 'Cora',
                'description' => 'Le haricot Cora est une variété de haricot vert particulièrement appréciée pour sa texture tendre et son goût délicat. Cultivé biologiquement, il produit des gousses longues et fines, parfaites pour la cuisine traditionnelle.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur douce et légèrement sucrée, texture tendre et croquante',
                'conservation' => 'Conserver au réfrigérateur dans un sac plastique perforé. Consommer dans les 3-5 jours.',
                'saison' => 'Juin à octobre',
                'usage' => 'Salades, plats cuisinés, accompagnements, conserves',
                'conditionnement' => json_encode(['10kg', '20kg']),
                'image' => '/img/produits/haricot-cora.jpg',
                'prix' => 1900.00,
                'bienfaits' => json_encode([
                    'Excellente source de protéines végétales',
                    'Riche en fibres qui régulent la glycémie',
                    'Contient du fer essentiel pour prévenir l\'anémie',
                    'Riche en vitamines B qui boostent l\'énergie',
                    'Propriétés antioxydantes et anti-inflammatoires'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'pasteque-baby-doll',
                'nom' => 'Pastèque',
                'variete' => 'Baby Doll',
                'description' => 'La pastèque Baby Doll est une variété compacte, parfaite pour les petites familles. Cultivée biologiquement, elle produit des fruits de taille moyenne avec une chair rouge sucrée et juteuse, et très peu de graines.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur très sucrée et juteuse, chair ferme et rafraîchissante',
                'conservation' => 'Conserver au réfrigérateur une fois coupée. Consommer dans les 5-7 jours.',
                'saison' => 'Mai à septembre',
                'usage' => 'Consommation fraîche, jus, salades de fruits, desserts',
                'conditionnement' => json_encode(['25kg', '60kg']),
                'image' => '/img/produits/pasteque-baby-doll.jpg',
                'prix' => 1100.00,
                'bienfaits' => json_encode([
                    'Très riche en eau (92%) pour une excellente hydratation',
                    'Contient du lycopène qui protège contre les maladies cardiovasculaires',
                    'Riche en citrulline qui améliore la circulation sanguine',
                    'Excellente source de vitamines A et C',
                    'Propriétés diurétiques et rafraîchissantes'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'slug' => 'melon-galia',
                'nom' => 'Melon',
                'variete' => 'Galia',
                'description' => 'Le melon Galia est une variété de melon musqué particulièrement appréciée pour son arôme exceptionnel et sa chair orange juteuse. Cultivé biologiquement, sa peau réticulée caractéristique en fait un fruit facilement reconnaissable.',
                'origine' => 'Côte d\'Ivoire',
                'gout' => 'Saveur très sucrée et parfumée, chair juteuse et aromatique',
                'conservation' => 'Conserver à température ambiante jusqu\'à maturation, puis au réfrigérateur. Consommer dans les 5-7 jours.',
                'saison' => 'Mai à septembre',
                'usage' => 'Consommation fraîche, salades de fruits, desserts, jus',
                'conditionnement' => json_encode(['25kg', '60kg']),
                'image' => '/img/produits/melon-galia.jpg',
                'prix' => 2100.00,
                'bienfaits' => json_encode([
                    'Riche en bêta-carotène qui améliore la vision et la peau',
                    'Excellente source de vitamine C qui renforce le système immunitaire',
                    'Contient du potassium qui régule la pression artérielle',
                    'Riche en antioxydants qui protègent contre le vieillissement',
                    'Propriétés hydratantes et rafraîchissantes'
                ]),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        DB::table('produits')->insert($produits);
    }
}
